### ISSUE TITLE
With malformed input: Unix error: Illegal seek

### ISSUE THREAD

**Issue by mayfrost** [drbig/snb#13]
It appears that any line not starting with a `-` spits out

    ERROR: Malformed input at line <line_without_dash>.
    Unix error: Illegal seek

As is the case than the accompanying file `help.md` works fine but not `README.md` or similar markdown. This is a show stopper currently but overall great program.

**Comment by drbig** [comment]
This is intentional: `snb` was never meant to be a Markdown editor. The choice of using most of Markdown format is merely for convenience (you can read/print the list anywhere and it should still be readable, or convertible to HTML/PDF with already available tools). There is plenty of Markdown editors out there, most have helpers for lists too.

As such I'm closing this issue.
